Implemented Mac Address type #72
NoxOrg/Nox.Generator pull request #126
Opened 2023-07-05 11:44 UTC by emir-sehovic1

2023-07-05 12:48 UTC, dejobratic commented on tests/Nox.Types.Tests/Types/MacAddress/MacAddressTests.cs
>  public class MacAddressTests
According to the latest info, test should be written using FluentAssertions. Can you please add the required changes here? 

https://regusit.atlassian.net/wiki/spaces/NOX/pages/3153264693/Test+Projects

You can find sample implementation here: https://github.com/NoxOrg/Nox.Generator/blob/main/tests/Nox.Types.Tests/Types/Volume/VolumeTests.cs

2023-07-05 12:48 UTC, dejobratic commented on src/Nox.Types/Types/MacAddress/MacAddress.cs
> +    private static readonly int MacAddressLengthInBytes = 6;
Can we change this to private const int?

2023-07-05 12:49 UTC, dejobratic commented on src/Nox.Types/Types/MacAddress/MacAddress.cs
> +    public new static MacAddress From(string value)
Can you please add comments on public methods?

2023-07-05 12:50 UTC, dejobratic requested changes
Looks good to me. Added some minor comments.

2023-07-06 07:30 UTC, dejobratic submitted a review, later dismissed
Looks good. Thanks.

2023-07-06 16:27 UTC, rochar approved these changes
looks good, just a small typo

2023-07-06 16:27 UTC, rochar commented on src/Nox.Types/Types/MacAddress/MacAddress.cs
> +/// <remarks>Placeholder, needs to be implemented</remarks>
you can remove the remark

2023-07-07 09:15 UTC, rochar requested changes

2023-07-07 09:15 UTC, rochar commented on src/Nox.Types/Types/MacAddress/MacAddress.cs
> +    public new static MacAddress From(string value)
can you rename the property value to something meaningful like macAddressText

2023-07-07 09:15 UTC, rochar commented on src/Nox.Types/Types/MacAddress/MacAddress.cs
> +    public static MacAddress From(ulong value)
same here, value has no good meaning

2023-07-07 09:52 UTC, rochar approved these changes

2023-07-07 09:53 UTC, merged