Make keys mandatory for entities
NoxOrg/Nox.Generator pull request #181
Opened 2023-07-07 09:26 UTC by ILoveMyTortoise

2023-07-07 09:28 UTC, ILoveMyTortoise commented
![image](https://github.com/NoxOrg/Nox.Generator/assets/129159439/a96f2f19-dd3d-469f-a2b7-30ae161aeccd)
![image](https://github.com/NoxOrg/Nox.Generator/assets/129159439/2fb784af-7e3d-4463-aa52-af58060f48f7)

2023-07-07 10:06 UTC, jan-schutte approved these changes

2023-07-07 10:10 UTC, rochar requested changes
nice.

Can you add a test to YamlFileValidationTests, with an incorrect yaml (no keys)

2023-07-07 14:38 UTC, alexandervlasenko submitted a review, later dismissed

2023-07-09 09:23 UTC, ILoveMyTortoise commented
> nice. Can you add a test to YamlFileValidationTests, with an incorrect yaml (no keys)

@rochar Actually, we already have a test with complex validation of error scenarios, Deserialize_WithNoxYamlSerializer_ThrowsException, so I've increased the error count. Maybe in the future we can add check for particular text error messages

2023-07-09 16:28 UTC, alexandervlasenko approved these changes

2023-07-10 06:46 UTC, jan-schutte approved these changes

2023-07-10 07:17 UTC, rochar approved these changes

2023-07-10 07:19 UTC, merged