Feature/password type
NoxOrg/Nox.Generator pull request #186
Opened 2023-07-07 11:06 UTC by becicajla

2023-07-13 06:41 UTC, gjorgji-grgovski-authoritypartners requested changes

2023-07-13 06:41 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Types/Types/HashedText/TypeOptions/HashedTextTypeOptions.cs
> +public class HashedTextTypeOptions
Can we update the Schema for this new TypeOptions?
https://github.com/NoxOrg/Nox.Generator#schemas-update

2023-07-13 06:41 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Types/Types/Password/Password.cs
> +    public static Password From(string value, PasswordTypeOptions options)
Please add XML Documentation comments

2023-07-13 06:41 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Types/Types/Password/PasswordTypeOptions/PasswordTypeOptions.cs
> +    public Regex PasswordContainsSympol { get; } = new(@"(.*[!@#$%^&*(),.?"":{}|<>\-_].*)+", RegexOptions.Compiled, new TimeSpan(0, 0, 1));
Typo: PassowrdContainsSymbol

2023-07-13 06:41 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Types/Types/Password/PasswordTypeOptions/PasswordTypeOptions.cs
> +public class PasswordTypeOptions
Can we update the Schema for this new TypeOptions?
https://github.com/NoxOrg/Nox.Generator#schemas-update

2023-07-20 07:20 UTC, gjorgji-grgovski-authoritypartners approved these changes
@becicajla please promote this Draft to a PR

2023-07-21 11:24 UTC, gjorgji-grgovski-authoritypartners commented
@rochar you can review this one, I resolved the opened conversations

2023-07-24 13:09 UTC, rochar requested changes

2023-07-24 13:09 UTC, rochar commented on src/Nox.Types/Types/Password/Password.cs
For maintenance purpose, to avoid having value objects of Value objects, see your EF configuration, does not seems simple.

 Its better IMO to use composition, or even repeat some code, and the Password should inherit from ValueObject<(string EncriptedPassword, string Salt) for example. Otherwise any change will affect both... we are using HasedhTextOption to create the password, does not seems right,

2023-07-25 10:28 UTC, rochar approved these changes

2023-07-25 11:05 UTC, merged