Initial/rest controllers generators
NoxOrg/Nox.Generator pull request #23
Opened 2023-06-27 14:07 UTC by alexandervlasenko

2023-06-27 17:29 UTC, ILoveMyTortoise approved these changes

2023-06-28 07:26 UTC, rochar requested changes
looks good, just a comment on tests and be able to see the generated class

2023-06-28 07:26 UTC, rochar commented on src/Nox.Generator/Presentation/Api/ApiGenerator.Rest/ApiControllerGenerator.cs
@alexandervlasenko can we add a test to see if the class is generated, similar to what we have?

2023-06-28 07:26 UTC, rochar commented on src/Nox.Generator/Presentation/Api/ApiGenerator.Rest/ApiControllerGenerator.cs
Can you provide a screen shoot of the generated class, so its easier to review, thks

2023-06-30 11:59 UTC, alexandervlasenko commented on src/Nox.Generator/Presentation/Api/ApiGenerator.Rest/ApiControllerGenerator.cs
Hi @rochar , I've added a new test and also a sample file into examples folder (src/SampleWebApp/Examples/CountriesApiController.cs) so no need in a screenshot.

Best regards

2023-07-03 11:21 UTC, rochar approved these changes

2023-07-03 11:22 UTC, jan-schutte approved these changes

2023-07-03 11:22 UTC, merged