Day of the week
NoxOrg/Nox.Generator pull request #263
Opened 2023-07-17 23:09 UTC by denisvieira-dev

2023-07-21 12:09 UTC, gjorgji-grgovski-authoritypartners requested changes

2023-07-25 12:58 UTC, gjorgji-grgovski-authoritypartners commented
Please rollback all deleted files

2023-07-25 13:06 UTC, gjorgji-grgovski-authoritypartners requested changes

2023-07-25 13:18 UTC, denisvieira-dev commented on src/Nox.Types/Enums/DayOfTheWeek.cs
> +public enum DayOfTheWeek
Done

2023-07-25 13:19 UTC, denisvieira-dev commented on src/Nox.Types/Types/DayOfWeek/DayOfWeek.cs
> +    public static new DayOfWeek From(int value)
Done

2023-07-25 13:19 UTC, denisvieira-dev commented on src/Nox.Types/Types/DayOfWeek/DayOfWeek.cs
>  public sealed class DayOfWeek : ValueObject<int, DayOfWeek>
Done

2023-07-25 14:47 UTC, denisvieira-dev commented on src/Nox.Types/Types/DayOfWeek/DayOfWeek.cs
> +    public static DayOfWeek From(DayOfWeek dayOfTheWeek)
Done

2023-07-25 16:22 UTC, gjorgji-grgovski-authoritypartners requested changes

2023-07-26 11:35 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-07-26 12:02 UTC, rochar requested changes
Looks good, just a small comment

2023-07-26 12:02 UTC, rochar commented on src/Nox.Types.Abstractions/Enums/DayOfTheWeek/DayOfTheWeek.cs
I would use System.DayOfWeek and avoid add anew type

2023-07-26 12:02 UTC, rochar commented on src/Nox.Types/Types/DayOfWeek/DayOfWeek.cs
> +
Add to WeekDay() and return System.DayOfWeek from the value

2023-07-26 15:19 UTC, rochar approved these changes

2023-07-27 10:15 UTC, rochar approved these changes

2023-07-27 10:42 UTC, merged