Implemented Formula type #82
NoxOrg/Nox.Generator pull request #322
Opened 2023-07-19 14:33 UTC by emir-sehovic1

2023-07-21 11:06 UTC, gjorgji-grgovski-authoritypartners approved these changes
All good with just a small comment, please mark it as Ready for Review

2023-07-21 11:11 UTC, emir-sehovic1 commented on src/Nox.Types.EntityFramework/Types/Formula/FormulaConverter.cs
> +    public FormulaConverter() : base(dt => dt.Value, dtValue => Formula.From(dtValue)) { }
Fixed, thanks

2023-07-25 10:36 UTC, rochar requested changes
looks good, small comments

2023-07-25 10:36 UTC, rochar commented on tests/Nox.Types.Tests/EntityFrameworkTests/Configuration/CountryDbConfiguration.cs
you can remove the db tests, this type will not be persisted on the database, will impact only the generators, we will generate a property with the formula

and the future dbconfiguration is no need, I will remove the ticket

thks

2023-07-25 10:36 UTC, rochar commented on src/Nox.Types.EntityFramework/Types/Formula/FormulaConverter.cs
please remove the converter

This type will not be persisted, and used only in the generatores level

2023-07-25 12:46 UTC, emir-sehovic1 commented
> looks good, small comments

Thanks for feedback @rochar , I've fixed the comments

2023-07-25 13:26 UTC, rochar approved these changes

2023-07-25 13:26 UTC, merged