Changes to encryptedtext type
NoxOrg/Nox.Generator pull request #327
Opened 2023-07-20 09:21 UTC by danield-ap

2023-07-25 09:27 UTC, rochar requested changes
looks good, just small comments

2023-07-25 15:13 UTC, rochar approved these changes

2023-07-25 15:13 UTC, rochar commented on src/Nox.EntityFramework.SqlServer/SqlServerEncryptedTextDatabaseConfigurator.cs
removing the max and min, we should not need the SQL Configuration and we can let EF to do it by default to binary (please confirm its binary)

2023-07-25 15:13 UTC, rochar commented on src/Nox.EntityFramework.Postgres/PostgresEncryptedTextDatabaseConfiguration.cs
we can also remove this, since we are removing Max and Min

2023-07-25 16:25 UTC, danield-ap commented on src/Nox.Types/Types/EncryptedText/EncryptedText.cs
> +    public new static EncryptedText From(byte[] value) => FromEncryptedString(value);
I think it depends on the use case. The most common scenario might be storing and retrieving data from a Database, if we are only planning on doing that it won't be necessary.
Other use case for encrypted text is communication. If this type will be used for sending data to another server/service, the other side will need to create the type from the ecnrypted byte array.

I removed the method for now.

2023-07-25 16:26 UTC, danield-ap commented on src/Nox.Types/Types/EncryptedText/EncryptedText.cs
> +    public static EncryptedText FromEncryptedString(byte[] value)
Method removed.

2023-07-25 16:26 UTC, danield-ap commented on src/Nox.Types.EntityFramework/Types/EncryptedText/EncryptedTextConverter.cs
> +    public EncryptedTextConverter() : base(encryptedText => encryptedText.Value, encryptedBase64 => EncryptedText.FromEncryptedString(encryptedBase64)) { }
Updated to use FromDatabase.

2023-07-25 16:59 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-07-26 12:06 UTC, rochar approved these changes

2023-07-26 12:06 UTC, merged