Features/212 nuid construction
NoxOrg/Nox.Generator pull request #330
Opened 2023-07-20 12:13 UTC by AndreyDegtyarev

Introduced code generation for Nuid type.
Added validation for NuidTypeOptions to check whether entity properties exist.

2023-07-20 14:21 UTC, rochar requested changes
please commit generated code, so I can continue the review

2023-07-20 14:23 UTC, rochar commented on src/Nox.Generator/Common/TemplateScriptsBridges/NoxSolutionCodeGeneratorStateBridge.cs
> +            scriptObject1.Import("CodeGeneratorPrivateFieldName", new Func<NoxSimpleTypeDefinition,
we will remove the option of include scriptObject, to make the template explicit and simple... this needs to be re think to be done with script objects

2023-07-21 10:45 UTC, rochar requested changes

2023-07-21 10:45 UTC, rochar commented on tests/Nox.Generator.Tests/ExpectedGeneratedFiles/Country.expected.g.cs
Nuid should be a get property, private to be set from the database without any logic 

Consider how this will be used by the application (Services / API), someone creates an Entity the controller or messaging receives this request, delegates to the Application Service that creates an Entity, how can it generate the Id?

And for the update use Case?

This should be immutable after the creation, update can/should only validate

2023-07-25 07:23 UTC, rochar requested changes
Looks good, just a few comments

2023-07-25 07:23 UTC, rochar commented on tests/Nox.Tests/NuidTypeTests.cs
> +            Assert.Equal(entity.Id, dbEntity.Id);
Use Fluent Assertions

2023-07-25 07:23 UTC, rochar commented on tests/Nox.Generator.Tests/ExpectedGeneratedFiles/Country.expected.g.cs
> +    				throw new ApplicationException("Immutable nuid property Id value is different since it has been initialized");
Create a specific exception for this Nox***Exception

2023-07-25 07:23 UTC, rochar commented on src/Nox.Types.Abstractions/TypeOptions/NuidTypeOptions.cs
> +    public string? Prefix { get; set; }
Add a comment, explaining the puposes, its optional, and and will be the prefix if this is not set

2023-07-25 07:23 UTC, rochar commented on src/Nox.Types.Abstractions/TypeOptions/NuidTypeOptions.cs
You need to add this options to NoxSimpleTypeDefinition and regenerate the schemas

2023-07-25 15:44 UTC, AndreyDegtyarev commented on src/Nox.Types.Abstractions/TypeOptions/NuidTypeOptions.cs
Has already added.

2023-07-26 08:48 UTC, rochar approved these changes

2023-07-26 08:48 UTC, rochar commented on src/Nox.Solution/Models/Domain/Entities/Entity.cs
> +            var relationships = Relationships
why are you change this in this PR?

code cleanup needs to be done in its own PR

2023-07-26 08:49 UTC, merged