MP-7751: TimeZoneCode database configuration.
NoxOrg/Nox.Generator pull request #351
Opened 2023-07-25 10:21 UTC by originalethanhunt

2023-07-25 16:37 UTC, gjorgji-grgovski-authoritypartners requested changes

2023-07-25 16:37 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Types.EntityFramework/Types/TimeZoneCode/TimeZoneCodeDatabaseConfiguration.cs
> +            .HasConversion<TimeZoneCodeConverter>();
TimeZoneCodeConverter have to use FromDatabase method.

2023-07-26 16:47 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-07-27 07:24 UTC, rochar approved these changes

2023-07-27 07:29 UTC, merged