MP-7793 [BS-8103] NOX - Database configuration for "Date"
NoxOrg/Nox.Generator pull request #389
Opened 2023-07-27 15:06 UTC by emir-sehovic1

- Implemented db configuration for Date nox type
- Upgraded underlying type to DateOnly since Nox.Types was upgraded to net7.0
- Added postgres integration tests

2023-07-28 22:39 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-07-29 14:12 UTC, rochar requested changes
looks good, one comment to validate

2023-07-29 14:12 UTC, rochar commented on src/Nox.EntityFramework.Postgres/PostgresDateDatabaseConfigurator.cs
I do not think we need any specific database configuration, EF should take car of all cases, for SQL for example: https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-data-type-mappings

since the converter already states is datetime

2023-07-31 09:29 UTC, rochar approved these changes

2023-07-31 09:44 UTC, merged