Currency Number Db configuration
NoxOrg/Nox.Generator pull request #390
Opened 2023-07-28 01:48 UTC by denisvieira-dev

2023-07-28 22:42 UTC, gjorgji-grgovski-authoritypartners commented
The title of the PRs should start with "MP-XXXX ........."

2023-07-28 22:47 UTC, gjorgji-grgovski-authoritypartners commented
The converter should use the "FromDatabase" method.

2023-07-30 21:14 UTC, gjorgji-grgovski-authoritypartners requested changes

2023-07-30 21:14 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Types.EntityFramework/Types/CurrencyNumber/CurrencyNumberDatabaseConfiguration.cs
> +            .HasConversion<CurrencyNumberConverter>();
Converters should use "FromDatabase"

2023-07-31 02:12 UTC, denisvieira-dev commented on src/Nox.Types.EntityFramework/Types/CurrencyNumber/CurrencyNumberDatabaseConfiguration.cs
> +            .HasConversion<CurrencyNumberConverter>();
Done

2023-07-31 09:31 UTC, rochar approved these changes

2023-08-01 21:16 UTC, danield-ap approved these changes

2023-08-02 10:45 UTC, merged