Features/387 global error handling sample web app
NoxOrg/Nox.Generator pull request #392
Opened 2023-07-28 05:08 UTC by AndreyDegtyarev

[OData] Ensure that Odata runtime exceptions are not swallowed

2023-07-28 08:02 UTC, rochar requested changes
Looks good, all can be a Nox implemenation, the sample webApp use this by default

for now we want to make Nox adoption and feature to be used only with AddNox() option

2023-07-28 08:02 UTC, rochar commented on src/SampleWebApp/Extensions/ApplicationExtensions.cs
we can add this by default in ServiceCollectionExtension.AddNoxLib

2023-08-01 09:04 UTC, AndreyDegtyarev commented on src/SampleWebApp/Extensions/ApplicationExtensions.cs
Moved to UseNox() extension method since middleware should be added in application's pipeline

2023-08-01 14:42 UTC, rochar approved these changes

2023-08-01 14:42 UTC, merged